### ISSUE TITLE
Implement chess_piece enum class for representing the chess pieces

### ISSUE THREAD

**Issue by hato1883** [hato1883/M6-Projekt#1]
Implement a class for chess pieces stored as enum (see [link](https://docs.python.org/3/library/enum.html) for more information) should contain a integer value representing a chess piece, also needs to have a value for no piece (example value  0).

This is so we can later do check such as:
`if chessboard[0][0].getPiece() == chess_piece.PAWN`
Instead of:
`if chessboard[0][0].getPiece() == 1`
Or similar.

**Comment by hahadude497** [comment]
#11 merge fixes this
