### ISSUE TITLE
implement valid_queen_move in class chess_board

### ISSUE THREAD

**Issue by JobaTheTired** [hato1883/M6-Projekt#13]
**chess_board #8 needs to be implemented first.**

### input 
from_pos is tuple: (row, column)
to_pos is tuple: (row, column)

row is int in [0,7]
column is int in [0,7]

### Behavior:
Checks whether desired move is valid for a queen

if yes -> return True
else -> return False

**Comment by hato1883** [comment]
Replaced by #34 #33
