### ISSUE TITLE
implement in_danger in class chess_board

### ISSUE THREAD

**Issue by JobaTheTired** [hato1883/M6-Projekt#19]
**chess_board #8 needs to be implemented first.**

### input:
- **self** - A reference to this board state (dose not need to be passed to method)
- **position** - a tuple with starting position in the 2d list Chessboard class

### Behavior: 
1. Searches if any enemy piece can attack destination square

## Output: Boolean value
**True**  - if position can be attacked by enemy piece
**False** - if position is not currently attacked

**Comment by hato1883** [comment]
fixed in #43
