### ISSUE TITLE
Implement the pawn promotion mechanic/rule in ChessBoard class

### ISSUE THREAD

**Issue by JobaTheTired** [hato1883/M6-Projekt#25]
Implement the pawn promotion mechanic/rule in ChessBoard #8 

https://en.wikipedia.org/wiki/Promotion_(chess)

When pawn reaches the opposite side, the pawn may be replaced with either a queen, rook, bishop or knight of same color.

**Comment by hato1883** [comment]
Fixed in main.py game loop
