### ISSUE TITLE
Implement method: is_abs_move_valid(self, origin: tuple, destination: tuple, options: list) -> bool

### ISSUE THREAD

**Issue by hato1883** [hato1883/M6-Projekt#32]
Method used to check the `MoveType.ABSOLUTE_TAKE` and `ABSOLUTE_MOVE` from #27 

# Method Implementation
## Name :
is_abs_move_valid(self, origin: tuple, destination: tuple, options: list) -> bool
## Input: 2 tuples, 1 bool
- **self** - A reference to this board state (dose not need to be passed to method)
- **origin** - a tuple with starting position in the 2d list Chessboard class
- **destination** - a tuple with move destination in the 2d list Chessboard class
- **options** - a list of MoveOptions( can be empty, but not None)

## Behavior:
1. if `MoveOption.TAKE in options` Check if destination is not ally
2. else Checks destination is empty
3. if `MoveOption.FIRST in options` Check if origin piece has **NOT** moved before
4. if `MoveOption.PROTECTED in options` Check if in_danger(pos) == True on destination and along the way

## Output: Boolean value
**False** - if destination is not empty or contains an allied piece depending on `can_take` bool
**True**  - if not (Empty or Enemy)

# Comments
Replaces #17

**Comment by hato1883** [comment]
Remade issue to feature new generalized version of a knight move. this will work basically the same as previous implementation but will be consistent with other methods.

**Comment by hato1883** [comment]
Updated implementation details to match update in project structure.

**Comment by JobaTheTired** [comment]
Done!
