### ISSUE TITLE
implement chess_board class, holds 2d-array [row][colum]

### ISSUE THREAD

**Issue by JobaTheTired** [hato1883/M6-Projekt#8]
Responsible for:
*Adding pieces
*removing pieces
*checking if a move is valid

attributes:
2-d array [row][colum] 

methods:
is_vaild(from_pos, to_pos) - return bool
add_piece( piece,  pos) return bool
remove_piece(pos) return bool

**Comment by hato1883** [comment]
This is completed but we still have sub issues in class.
Closing this and adding new.
